### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by NaitorStudios** [rodamaral/smw-tas#20]
Hey, notei que você é brasileiro, então vou falar em português...
Estou desenvolvendo um remake de SMW, nisso, notei que nessa sua ferramenta mostra algumas coisas como todos os sensores de colisão e alguns itens da camera...
Eu gostaria de saber como funciona os sensores de colisão, pq há dois embaixo, se você faz ideia como funciona a detecção das rampas, e talvez um pouco sobre a camera...
Você poderia me ajudar, por favor?

**Comment by rodamaral** [comment]
Os dois pontos brancos embaixo do Mario são os pés, usados para detectar o chão abaixo.
Se existe um bloco sob algum dos dois pés, o Mario não cai. Caso contrário, cai.

Se algum dos blocos sob o Mario é um muncher e o outro não, então o ponto médio entre os pés é levado em conta para ver se o Mario será ferido ou não. Esse mesmo ponto médio é o que importa caso o Mario esteja numa rampa. As rampas possuem uma lógica um pouco mais complicada e que permite que o Mario atravesse, caso esteja subindo lentamente e tenha velocidade horizontal suficiente.

Quanto a câmera, o script também mostra. A lógica não é trivial, mas com o visor fica fácil ver o mecanismo (Menu > Show/hide > Show camera region). Basicamente, existe uma região retangular que se desloca para trás do Mario, quando ele a atinge. O objetivo é ter uma visão maior na direção que o personagem se move. Esse tweet ilustra isso muito bem.
https://twitter.com/Masterjun3/status/1052615381586718721

Qualquer dúvida adicional, pode falar.

**Comment by NaitorStudios** [comment]
Muito obrigado pela atenção, será de grande ajuda!

Certo, os dois sensores nos pés é o que seguram ele no solo, o unico no topo é o que o impede de entrar em blocos e tetos, noto que se o sensor do topo não colide com o teto/blocos, ele é puxado para os lados, isso é o que facilita pular entre dois blocos... Isso acontece só por causa dos sensores laterais o empurrando para fora?

Há dois sensores laterais em cada lado, existe um proposito para isso?
Eu também notei que o + no centro é tanto usado para escalar quanto para detecção de esmagamento, para esmagamento, os outros sensores tem alguma coisa a ver? Digo, exemplo, quando o + colide com algo sólido, ele automaticamente é esmagado ou outros sensores também devem estar em contato com algo sólido?

Nos sensores que o script mostra, há um cinza preenchido semitransparente que pega quase todo o sprite e outro vermelho sem preenchimento, qual são exatamente as funções deles? Eu imaginaria que o vermelho tenha a ver com colisão com inimigos mas posso estar enganado...

Você citou um tal de ponto médio, não entendi bem se ele é um ponto invisivel entre os dois pés ou se por exemplo ele é o sensor + que aparece no centro do Mario... Poderia especificar?

Mas acho que minha maior dúvida é quanto as rampas, a camera eu meio que já tenho funcionando (embora ainda não tenha total certeza de do que é levado em consideração para ela ancorar, que imagino que é o que causa o bug de uma fase que faz com o que o Mario possa sair da camera subindo uma rampa)

Os tiles das rampas são detectados como algo diferente dos tiles normais e isso causa o funcionamento diferente dos sensores ou há outra coisa por trás? Pensei nisso pq aparentemente spiketops veem as rampas como tiles não-diagonais...
Algum tempo atrás cheguei a pensar que os sensores se alinhavam com diferentes angulos de rampas, e que talvez isso permitisse com que o jogo soubesse qual o ângulo, mas imagino que não seja bem isso...

A interação com plataformas móveis também me intrigam um pouco, mas imagino que pelo menos a cinza que gira em torno de um bloco o mario é substituido por outro que é fixo na plataforma, não?
Tenho impressão que as vezes é possivel ver dois marios ao saltar dessas plataformas

**Comment by rodamaral** [comment]
> ele é puxado para os lados, isso é o que facilita pular entre dois blocos... Isso acontece só por causados sensores laterais o empurrando para fora?

Os dois sensores laterais servem para impedir que o Mario entre nas pareces. Se ao menos um deles toca um bloco sólido, a velocidade é zerada e o Mario é deslocado, 1 pixel a cada frame, para fora do bloco.

> um cinza preenchido semitransparente que pega quase todo o sprite e outro vermelho sem preenchimento, qual são exatamente as funções deles?

O vermelho é o hitbox para inimigos (ou qualquer outro sprite). A semitransparência só serve para deixar a visualização melhor. Note que SMW tem vários tipos de hitboxes diferentes. Sprite vs sprite, por exemplo, utiliza outro tipo de retângulo.

> Eu também notei que o + no centro é tanto usado para escalar quanto para detecção de esmagamento, para esmagamento, os outros sensores tem alguma coisa a ver? 

O "+" serve para empurrar o Mario pra esquerda, caso esteja dentro de blocos. Ou para esmagar o Mario, caso o pé e a cabeça estejam também tocando um sólido. Veja o 'blocked status'.

> Você citou um tal de ponto médio, não entendi bem se ele é um ponto invisivel entre os dois pés ou se por exemplo ele é o sensor + que aparece no centro do Mario... Poderia especificar?

Este ponto está exatamente sob o "+", mas na altura dos pés.

> bug de uma fase que faz com o que o Mario possa sair da camera subindo uma rampa

Note que o comportamento vertical da câmera é totalmente distinto do horizontal. As fases possuem configuração sobre como a câmera deve subir. No Lunar Magic, você vê isso melhor.

> Os tiles das rampas são detectados como algo diferente dos tiles normais e isso causa o funcionamento diferente dos sensores ou há outra coisa por trás?

Não entendi a pergunta. Se quiser, pode linkar screenshots aqui. A física das rampas é algo complicado que merece um textão próprio para explicar. Até mesmo a maioria dos TASers não sabe como funciona exatamente, apenas o que é preciso fazer para clippar.

> A interação com plataformas móveis também me intrigam um pouco

A interação entre o Mario e as plataformas sólidas são outro tópico em que a física é estranha Estando na mesma posição, é possível subir e não subir nelas caso o Mario esteja pequeno/grande ou segurando ou não um item. Tem a ver com a posição do sprite dentro da tela, não com a posição absoluta.

**Comment by NaitorStudios** [comment]
Então, o hitbox vermelho: Colisão com inimigos
O hitbox cinza semitransparente (parece ter um tamanho e diferente do hitbox vermelho), não entendi bem pra que serve, mas entendi que a semitransparencia é só pra visualização...

>  "+" serve para empurrar o Mario pra esquerda, caso esteja dentro de blocos.

Ele sempre é puxado para a esquerda? Achei que tivesse haver com qual sensor lateral é tocado

Voltando as rampas, o que eu quiz dizer é: o jogo consegue diferenciar solo normal e as rampas, e de alguma forma utiliza isso para decidir se ele deve subir uma rampa ou considera-la uma parede? Ou é algo totalmente dependente dos sensores e colisão?

Outra coisa que eu noto das rampas, subindo ou descendo elas, ele usa o ponto médio para posicionar o sprite, ignorando os sensores dos pés... E rampas como as da caverna, não são tiles com traços retos, mas tem pequenos detalhes/"pedregulhos", então, por trás do tile, há um shape da rampa sem esses detalhes, que é usado pelos sensores ou estando nas rampas é usado alguma formula pra saber a altura dele em relação a posição no tile?

Se puder explicar o que souber sobre a interação com as rampas eu agradeço muito...
Eu sei que muita gente diz que essa parte no jogo é um caos e que é um milagre funcionar, mas é importante pra mim replicar o mais próximo possivel

Edit: aaaahh outra coisa, noto que o personagem consegue pular de dentro pra fora de qualquer chão, mas não consegue atravessar os tetos virados para baixo e pros lados, faz ideia de como ele diferencia?

**Comment by rodamaral** [comment]
Nesse fim de semana, eu vou tentar escrever um texto ilustrativo sobre como as rampas funcionam, já que elas não dependem apenas da posição e velocidade atuais. Sobre o chão que pode ser atravessados de baixo para cima (como a nuvemzinha), os tiles são feitos para isso mesmo, eles não checam a cabeça do Mario nem empurram para fora.

**Comment by NaitorStudios** [comment]
Fantastico! Muito obrigado mesmo pela ajuda!
Eu fiquei fascinado pelo seu script desde que descobri, é realmente muito informativo, e imagino que deva ser bem útil para coisas como encontrar bugs, speedrun e injeção de código arbitrario =D

Ah, e falei desses tiles pelo seguinte, quando você "clipa" dentro de qualquer chão, o "miolo" não parece sólido, somente as bordas, mas especialmente a borda de cima sempre permite pular de baixo para cima (ou de dentro para fora), então imagino que eles são tiles especiais também, certo?
O mais curioso é que bolas de fogo sempre seguem reto quando dentro desse miolo contanto que as bordas sejam todas sólidas, nunca entendi rs

**Comment by NaitorStudios** [comment]
Alguma novidade? :D

**Comment by NaitorStudios** [comment]
Ainda esperando por algo, mas blz :V 
Eu entendo que você tem outras coisas a fazer

**Comment by rodamaral** [comment]
Olá @FuurioBR.

Deixei esse issue de lado esse tempo todo por falta de tempo, porque o assunto é realmente complexo e porque foge um pouco do objetivo desse repositório. Se você quiser ainda estiver interessado, visite o Discord que temos sobre SMW e que engloba tanto scripting, quando a mecânica do jogo e fazer TAS.

(link limitado a 5 usuários 👇)
https://discord.gg/6eqVQTf

**Comment by NaitorStudios** [comment]
Okay, muito obrigado pelo convite!
