### ISSUE TITLE
Problem trying to run in lsnes

### ISSUE THREAD

**Issue by nambona890** [rodamaral/smw-tas#21]
I've copied the font files to my lsnes data folder, and am using the lsnes rr2-b24 version specified in the README, but all that happens when I run the lua script is the window expands, and I get countless `Error running Lua callback: Argument #2 to memory.readregion must be integer` errors.
[Here's what the window looks like.](https://i.imgur.com/3uv6Tjv.png)

**Comment by rodamaral** [comment]
Screenshot shows **β23**. This issue is caused by an old version of lsnes. Try to use Beta - rr2-β24 from the page
http://tasvideos.org/Lsnes.html
